// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.IncomeTaxBrackets
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("year")]
        public long Year { get; set; }

        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("brackets")]
        public Brackets Brackets { get; set; }

        [JsonProperty("standard_deduction")]
        public StandardDeduction StandardDeduction { get; set; }

        [JsonProperty("lastUpdated")]
        public DateTimeOffset LastUpdated { get; set; }
    }

    public partial class Brackets
    {
        [JsonProperty("single")]
        public HeadOfHousehold[] Single { get; set; }

        [JsonProperty("married_filing_jointly")]
        public HeadOfHousehold[] MarriedFilingJointly { get; set; }

        [JsonProperty("married_filing_separately")]
        public HeadOfHousehold[] MarriedFilingSeparately { get; set; }

        [JsonProperty("head_of_household")]
        public HeadOfHousehold[] HeadOfHousehold { get; set; }
    }

    public partial class HeadOfHousehold
    {
        [JsonProperty("rate")]
        public double Rate { get; set; }

        [JsonProperty("min")]
        public long Min { get; set; }

        [JsonProperty("max")]
        public long Max { get; set; }
    }

    public partial class StandardDeduction
    {
        [JsonProperty("single")]
        public long Single { get; set; }

        [JsonProperty("married_filing_jointly")]
        public long MarriedFilingJointly { get; set; }

        [JsonProperty("married_filing_separately")]
        public long MarriedFilingSeparately { get; set; }

        [JsonProperty("head_of_household")]
        public long HeadOfHousehold { get; set; }
    }
}
